name: Circle Workflow

on: 
  # so these line up to a file in the .circleci/ directory as <event-name>-<type>.yml
  # e.g. issue_comment-created.yml and issues-opened.yml
  issue_comment:  
    types: [created]
  issues:
    types: [opened, closed] 
  release:
    types: [unpublished]


jobs:
  circle-workflow:
    name: ${{ github.event_name }}-{{ github.event.type }} workflow
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - run: git checkout HEAD^
    - name: Replace config
      run: cp .circleci/${{ github.event_name }}-{{ github.event.type }}.yml .circleci/config.yml
    - name: commit-push_branch-test
      uses: dsayling/commit-branch-check-action@v0.0.8
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        files: ".circleci/config.yml"
        commit-message: "Run workflow"
        dest-branch: ${{ github.event_name }}-{{ github.event.type }}
        verify-checks: true
        delete-after-checks: true
