name: Test PR
# This workflow simply runs a circleci workflow to ensure any change to the action version is successful

on: pull_request

jobs:
  circle-workflow:
    name: PR test workflow
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Replace config
      run: cp .circleci/release-created.yml blahblah.txt
    - name: commit-push_branch-test
      uses: dsayling/commit-branch-check-action@use-src-ref
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        files: "blahblah.txt"
