name: Test PR
# This workflow simply runs a circleci workflow to ensure any change to the action version is successful

on: pull_request

jobs:
  circle-workflow:
    name: PR test workflow
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
    - name: Replace config
      run: cp .circleci/release-created.yml .circleci/config.yml
    - name: commit-push_branch-test
      uses: dsayling/commit-branch-check-action@v0.1.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        files: ".circleci/config.yml"
        commit-message: "Run test PR workflow"
        dest-branch: pr-test-workflow
        verify-checks: true
        delete-after-checks: true
